"""test

Revision ID: 0002
Revises: 0001
Create Date: 2026-04-29 16:19:40.478409
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('chapter_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chapter_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('display_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('standard', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=True))
        batch_op.create_index('ix_documents_book_chapter', ['book_id', 'chapter_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_book_id'), ['book_id'], unique=False)
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_book_id'))
        batch_op.drop_index('ix_documents_book_chapter')
        batch_op.drop_column('subject')
        batch_op.drop_column('standard')
        batch_op.drop_column('display_name')
        batch_op.drop_column('chapter_title')
        batch_op.drop_column('chapter_number')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###
